trigger: none

variables:
  - template: config.yml
  - group: FinOps-func-GVdasa

pool: azp-gvdasa-full-01

stages:
  - stage: 'Build_function'
    displayName: 'Build function'
    jobs:
    - job: 'Build'
      displayName: 'Build'

      steps:
      - task: NuGetToolInstaller@1
        displayName: 'Instalar Nuget'

      - task: DotNetCoreCLI@2
        displayName: Restore
        inputs:
          command: restore
          feedsToUse: 'select'
          vstsFeed: 'Feed_NAP'
          includeNuGetOrg: true
          projects: |
            src/Gvdasa.FinOpsApi.AzureFunctions/Gvdasa.FinOpsApi.AzureFunctions.csproj

      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          arguments: '--configuration Release'
          feedsToUse: 'select'
          vstsFeed: 'Feed_NAP'
          includeNuGetOrg: true
          projects: |
            src/Gvdasa.FinOpsApi.AzureFunctions/Gvdasa.FinOpsApi.AzureFunctions.csproj

      - task: DotNetCoreCLI@2
        displayName: Publish
        inputs:
          command: publish
          publishWebProjects: false
          modifyOutputPath: true
          arguments: ' src/Gvdasa.FinOpsApi.AzureFunctions/Gvdasa.FinOpsApi.AzureFunctions.csproj --configuration Release --output $(build.artifactstagingdirectory)/${{ variables.ArtifactName }}'
          zipAfterPublish: True

      - script: |
            echo "build.artifactstagingdirectory: $(build.artifactstagingdirectory)/${{ variables.ArtifactName }}"
        displayName: 'debug variables'

      - publish: $(Build.ArtifactStagingDirectory)/${{ variables.ArtifactName }}
        artifact: '${{ variables.ArtifactName }}'
        condition: succeeded()