variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    Ambiente: prod
  ${{ elseif eq(variables['Build.SourceBranchName'], 'homolog') }}:
    Ambiente: hml
  ${{ else }}:
    Ambiente: dev

  ArtifactName: 'FinOpsBuildApi-${{ variables.Ambiente }}'
