trigger: none

resources:
  pipelines:
    - pipeline: FinOps-back-build
      source: FinOps-Platform\FinOps-back-build
      trigger: true

  repositories:
    - repository: DEVOPS
      type: git
      name: NAP/_git/DevOps
      ref: 'refs/tags/v3.0.3'

variables:
  - template: config.yml
  - group: FinOps-Api-${{ variables.Ambiente }}-GVdasa
  - group: Terraform
  - group: "ServiceBus-${{ variables.Ambiente }}"
  - group: "apim-gateway-${{ variables.Ambiente }}"

pool: azp-gvdasa-be-01

stages:
  - template: ./deploy-pipeline-template.yml@DEVOPS
    parameters:
      Ambiente: ${{ variables.Ambiente }}
      ArtifactName: ${{ variables.ArtifactName }}
      serviceUrl: https://$(NomeAplicacao)-${{ variables.Ambiente }}-wa.azurewebsites.net
      ApiId: "finops" 
      ApiDisplayName: "finops" 
      sourcePipeline: "FinOps-back-build" 
      SetorContainerBackendTerraform: "servicosbase"
      tfVars: '-var "aplicacao=$(NomeAplicacao)" -var "ambiente=$(Ambiente)" -var webhookUrlTeams=$(webhookUrlTeams)'
      tipo: 'back-dot-net'
      ApiId: "gvmodeloExemploBack" # substituir pelo nome EX. projeto-test
      ApiDisplayName: "GVmodeloExemploBack" # exemplo "test-project"
      sourcePipeline: "GVmodeloExemploBack-build" # EX. TestProject-back-deploy
      packageForLinux: '**/*.zip'
      tipo: 'back-dot-net'
