trigger: none

# Pipeline dedicado para infraestrutura do GVmodeloExemplo-back
# Execute este pipeline antes do deploy da aplicação ou quando houver mudanças na infraestrutura

resources:
  repositories:
    - repository: DEVOPS
      type: git
      name: NAP/_git/DevOps
      ref: 'refs/heads/version4'

parameters:
  - name: skipValidateDestroy
    displayName: '🛡️ Permitir Destruição (⚠️ false=seguro, true=permite destroy automático)'
    type: boolean
    default: false

variables:
  - template: config.yml
  - group: GVmodeloExemploBack-${{ variables.Ambiente }}-GVdasa
  - group: Terraform

pool: azp-gvdasa-full-01

stages:
  # 🏗️ Deploy da infraestrutura
  - template: ./templates/terraform/terraform-stage.yml@DEVOPS
    parameters:
      Ambiente: '${{ variables.Ambiente }}'
      NomeAplicacao: '$(NomeAplicacao)'
      ServiceConnection: '$(ServiceConnection)'
      TerraformAccessKey: '$(TerraformAccessKey)'
      workingDirectoryTF: '$(System.DefaultWorkingDirectory)/pipelines/terraform'
      tfVars: '-var "aplicacao=$(NomeAplicacao)" -var "ambiente=$(Ambiente)" -var webhookUrlTeams=$(webhookUrlTeams)'
      backendConfigKeyTF: '$(Ambiente)/$(NomeAplicacao)api.tfstate'
      tfVersionTF: '1.9.8'
      SetorContainerBackendTerraform: "nap"
      skipValidateDestroy: '${{ parameters.skipValidateDestroy }}'