<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Gvdasa.FinOpsApi.Domain</AssemblyName>
    <RootNamespace>Gvdasa.FinOpsApi.Domain</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Gvdasa.FinOpsApi.Modelos\Gvdasa.FinOpsApi.Modelos.csproj" />
    <ProjectReference Include="..\Gvdasa.FinOpsApi.Infra\Gvdasa.FinOpsApi.Infra.csproj" />
  </ItemGroup>
</Project>
