<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <AssemblyName>Gvdasa.FinOpsApi.WebApi</AssemblyName>
    <RootNamespace>Gvdasa.FinOpsApi.WebApi</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
   <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.18.1" />
    <PackageReference Include="FluentValidation" Version="11.9.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.9.0" />
    <PackageReference Include="Flurl.Http" Version="4.0.2" />
    <PackageReference Include="GVdasa.Permissoes" Version="0.6.0" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="MimeTypeMapOfficial" Version="1.0.17" />
    <PackageReference Include="SharpGrip.FluentValidation.AutoValidation.Mvc" Version="1.4.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.4" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.1" />
    <PackageReference Include="Serilog.Sinks.ApplicationInsights" Version="4.0.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.22.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.4" />
    <PackageReference Include="DateOnlyTimeOnly.AspNet.Swashbuckle" Version="2.1.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Gvdasa.FinOpsApi.Domain\Gvdasa.FinOpsApi.Domain.csproj" />
    <ProjectReference Include="..\Gvdasa.FinOpsApi.Infra\Gvdasa.FinOpsApi.Infra.csproj" />
    <ProjectReference Include="..\Gvdasa.FinOpsApi.Modelos\Gvdasa.FinOpsApi.Modelos.csproj" />
  </ItemGroup>
</Project>
